require:
  - solidus_dev_support/rubocop

FactoryBot/CreateList:
  Enabled: false

FactoryBot/AssociationStyle:
  Enabled: false

FactoryBot/FactoryNameStyle:
  Enabled: false

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.2 # Matching the .github/workflow/lint.yml ruby version
