version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1
  solidusio_extensions: solidusio/extensions@volatile

jobs:
  run-specs-with-sqlite:
    executor:
      name: solidusio_extensions/sqlite
      ruby_version: '3.1'
    steps:
      - browser-tools/install-chrome
      - solidusio_extensions/run-tests
  run-specs-with-postgres:
    executor:
      name: solidusio_extensions/postgres
      ruby_version: '3.1'
    steps:
      - browser-tools/install-chrome
      - solidusio_extensions/run-tests
  run-specs-with-mysql:
    executor:
      name: solidusio_extensions/mysql
      ruby_version: '3.1'
    steps:
      - browser-tools/install-chrome
      - solidusio_extensions/run-tests
  lint-code:
    executor:
      name: solidusio_extensions/sqlite-memory
      ruby_version: '3.1'
    steps:
      - solidusio_extensions/lint-code

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-with-sqlite:
          context: acts_as_tenant
      - run-specs-with-postgres:
          context: acts_as_tenant
      - run-specs-with-mysql:
          context: acts_as_tenant
      - lint-code:
          context: acts_as_tenant

  "Weekly run specs against main":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - main
    jobs:
      - run-specs-with-sqlite:
          context: acts_as_tenant
      - run-specs-with-postgres:
          context: acts_as_tenant
      - run-specs-with-mysql:
          context: acts_as_tenant
